#!/bin/bash

# Platform detection
PLATFORM=`uname`
if [[ $PLATFORM == 'Darwin' ]]; then
    PLATFORM='MacOSX'
elif [[ $PLATFORM == 'Linux' ]]; then
    PLATFORM='Linux'
elif [[ $PLATFORM == 'SunOS' ]]; then
    PLATFORM='Solaris'
elif [[ $PLATFORM == 'FreeBSD' ]]; then
    PLATFORM='FreeBSD'
fi

# Make 'less' the default man page reader
export MANPAGER="/usr/bin/less"

SSH_REMOTE_PORT=46836

# Remote hosts
SOE_HOST=soe.ucsc.edu
SOE_USER=bmatsuo
SOE=$SOE_USER@$SOE_HOST
SWINGDANCE_HOST=swingdance.cse.ucsc.edu
SWINGDANCE_USER=bmatsuo
SWINGDANCE=$SWINGDANCE_USER@$SWINGDANCE_HOST
CAMPUSROCKS_HOST=campusrocks.soe.ucsc.edu
CAMPUSROCKS_USER=bmatsuo
CAMPUSROCKS=$CAMPUSROCKS_USER@$CAMPUSROCKS_HOST
# Local network hosts
MACMINI_HOST=HouseOfGaga.local
MACMINI_USER=bryan
MACMINI=$MACMINI_USER@$MACMINI_HOST
MACBOOK_HOST=Huckleberry
MACBOOK_USER=Diesel
MACBOOK=$MACBOOK_USER@$MACBOOK_HOST
NETBOOK_HOST=magilla
NETBOOK_USER=bryan
NETBOOK=$NETBOOK_USER@$NETBOOK_HOST

# Template for new hosts.
# XXXX_HOST=""
# XXXX_USER=""
# ="$XXXX_USER:$XXXX_HOST"
