#!/bin/bash
# Modify environment variables used by programs.

# Set your text editor for things like 'git commit'
export EDITOR=/usr/bin/vim

# Add the paths to specific program's binaries.
# export PATH="$HOME/local/MATLAB/R2010b/bin:$PATH"

# Add necessary Macports paths to variables.
if [[ -d /opt/local ]]; then
    export PATH="/opt/local/bin:/opt/local/sbin:"$PATH
    export MANPATH="/opt/local/man:"$MANPATH
    export PERL5LIB="/opt/local/lib/perl5:"$PERL5LIB
    # LIBRARY_PATH is not necessary here for some reason?
    # CPLUS_INCLUDE_PATH is not necessary here for some reason?
fi

# Setup a user local install space at ~/local
if [[ -d ~/local ]]; then
    export LIBRARY_PATH="$HOME/local/lib:"$LIBRARY_PATH
    export CPLUS_INCLUDE_PATH="$HOME/local/lib:"$CPLUS_INCLUDE_PATH
    export PATH="$HOME/local/bin:$HOME/local/sbin:"$PATH
    export MANPATH="$HOME/local/man:"$MANPATH
    export PERL5LIB="$HOME/local/share/perl/5.10.1:$HOME/local/share/perl:$HOME/local/lib/perl5:"$PERL5LIB
    export PYTHONPATH="$HOME/local/lib/python2.6/site-packages:$HOME/local/lib/python2.6:$PYTHONPATH"
fi

export PATH="$HOME/Archive/Code/Go/owned/app-engine/google_appengine:$PATH"
