#!/bin/bash

REDWOOD="$HOME/Archive/LEEPS/redwood/src/"
PYTHONPATH="$REDWOOD:$PYTHONPATH"
export PYTHONPATH
export GOROOT="$HOME/local/src/go"
#export GOARCH=386
export GOBIN="$HOME/local/bin"
export GOPATH="$HOME/Projects/Go/Managed:$HOME/Projects/Go/Owned:$HOME/Projects/Go/Forked:$HOME/Projects/Go/Local:$GOPATH"
export PATH=`echo $GOPATH | sed -E 's/:?$/:/' | sed -E 's!/?:!/bin:!g'`:"$GOROOT/bin:$GOBIN:$PATH"
export GONEWROOT="$HOME/Archive/Code/GoNew"
export GOMAXTHREADS=5
export PATH="$HOME/.gem/1.8/bin:$PATH"
