#!/bin/bash

if [ -e "$HOME/.fehbg" ]; then
    eval `cat "$HOME/.fehbg"` &
fi

if which synclient 2>/dev/null; then
    # BUG:
    # This appears to break the trackpad completely, which is better than it
    # registering accidental touches.
    synclient "AreaRightEdge=1" &
fi

$HOME/.config/xkbmaps/pc105 &

stalonetray --dockapp-mode --icon-size 12 --max-geometry 0x24 &

sleep 1

$HOME/bin/dockapp-cpu -window.geometry=24x12 -ignore=cpu &

sleep 1

if [ -n "$(ls /sys/class/power_supply | grep -i battery)" ]; then
    dockapp-battery \
        -window.geometry  '48x12' \
        -battery.geometry '22x10+1+1' \
        -text.geometry    '24x10+23+1' \
        -text.fontsize    10 \
        '{{percent .fraction}}' \
        '{{durShort .remaining}}' &

    sleep 1
fi

lal --bold --color black --fontsize 10 --height 12 &

sleep 1

volumeicon &

sleep 1

xautolock -time 3 -locker slock &
