#!/bin/bash

eval `cat $HOME/.fehbg` &

# BUG: this appears to break the trackpad completely, which is better than it
# registering accidental touches.
synclient "AreaRightEdge=1" &

$HOME/.config/xkbmaps/pc105 &

$HOME/.config/openbox/lal/lal --bold --color black &

dockapp-cpu -window.geometry=40x20 -ignore=cpu &

dockapp-battery \
    -window.geometry  '40x20' \
    -battery.geometry '38x18+1+1' \
    -text.geometry    '38x18+1+1' \
    '{{percent .fraction}}' \
    '{{durShort .remaining}}' &

stalonetray --dockapp-mode &

xautolock -time 3 -locker slock &
